[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

build_flags =
  -std=gnu++17
  -Wall
  -Wextra
  -Werror=return-type
  ; Fill these (recommended) without committing secrets:
  ; -DWIFI_SSID=\"yourssid\"
  ; -DWIFI_PASS=\"yourpass\"
  ; -DIO_USERNAME=\"kichsatst\"
  ; -DIO_KEY=\"your_adafruit_io_key\"

lib_deps =
  knolleary/PubSubClient@^2.8
  bblanchon/ArduinoJson@^6.21.3

lib_ldf_mode = chain+
